name: 'OAS-gen Action'
description: 'Generates an OpenAPI specification of a Spring project and uploads the specification as a job artifact'

inputs:
  mvn_src_path:
    description: 'Path to the Maven directory'
    required: true
    default: ""

runs:
  using: "composite"
  steps:
      - name: 'Run OAS-gen tool on MVN src folder'
        run: docker run -v ${{inputs.mvn_src_path}}:/project alexx882/oas-gen:1.0 /project /project/target/docker/out/oas
        shell: bash
      - name: 'Upload artifact'
        uses: actions/upload-artifact@v4
        with:
          name: 'OpenAPI specifications'
          path: ${{inputs.mvn_src_path}}/target/docker/out/oas*
